### ISSUE TITLE
Error when Opening Activity Settings after Implementation

### ISSUE THREAD

**Issue by miguelalbano** [catalyst/moodle-mod_observation#120]
Module has been installed, latest version, on v4.0. No issues on installation.

Activity is added and configured. Observation points added. No issues.

Then, trying to go to the Activity Settings page, unable.

Exception - Attempt to assign property "text" on null

[More information about this error](https://docs.moodle.org/400/en/error/moodle/generalexceptionmessage)
Debug info:
Error code: generalexceptionmessage
Stack trace:

    line 84 of /mod/observation/mod_form.php: Error thrown
    line 588 of /course/moodleform_mod.php: call to mod_observation_mod_form->data_preprocessing()
    line 153 of /course/modedit.php: call to moodleform_mod->set_data()

Output buffer: <br /> <b>Warning</b>: Undefined property: stdClass::$introformat in <b>PATH/course/modlib.php</b> on line <b>754</b><br />

Other than that, it does work without issue.

**Comment by matthewhilton** [comment]
This should be fixed now by https://github.com/catalyst/moodle-mod_observation/pull/123 - please reopen if it is not fixed
