### ISSUE TITLE
As a coordinator, I can change the tutor/observer assigned to a timeslot

### ISSUE THREAD

**Issue by unxpctederr** [catalyst/moodle-mod_observation#19]
**Acceptance Criteria**

- [x] Given I am a coordinator and am viewing all the time slots, I can select a timeslot to edit and change the tutor for that time slot

**Comment by Gerrrrad** [comment]
This has been mostly done within #3 when creating the time slot session the coordinator selects the observer

**Comment by Gerrrrad** [comment]
This has been pushed to finished because it was merged within #3 and a coordinator can view the coordinator and choose an observer from a list of users with either - non-editing teacher, teacher, or manager
