### ISSUE TITLE
Refactor session marking page 

### ISSUE THREAD

**Issue by unxpctederr** [catalyst/moodle-mod_observation#71]
As Peter suggested, move Submit observation and cancel observation buttons out of dropdown, and onto the main page, but ensure they have a confirmation box attached to them.

**Comment by Gerrrrad** [comment]
Confirmation box example found under Quiz mod  but maybe more difficult to implement than originally thought, it looks like a JS file needs to be created to make the confirmation window work correctly 

Example - Quiz/report/overveiw/report.php
with JS file - quiz/yui/build/moodle-mod_quiz-toolboxes.js

**Comment by unxpctederr** [comment]
You can implement them using the $OUTPUT api as well - I implemented it on another branch - see example here https://github.com/catalyst/moodle-mod_observation/blob/5f66b346729fe0545628ae5d860cce92d95ded4d/assignstudents.php

**Comment by unxpctederr** [comment]
Basically the $OUTPUT->confirm will redirect to the same page, and you give it a confirm URL and a reject URL, and then on that page you can then check the URL parameters to see if the confirmation was confirmed or rejected and run functions accordingly.
