### ISSUE TITLE
As a student, I want to receive a confirmation of my registration, so that I know I’m registered

### ISSUE THREAD

**Issue by unxpctederr** [catalyst/moodle-mod_observation#9]
**Acceptance Criteria**

- [x] <s> Given that I am a student, when my booking is confirmed, then a confirmation is displayed on screen </s> - will be implemented seperately by #10 
- [x] Given that I am a student, when I have confirmed my time slot booking, then I receive an email to my moodle registered email

**Comment by Gerrrrad** [comment]
Currently blocked by #8
